---
driver:
  name: digitalocean

driver_config:
  require_chef_omnibus: '11.16.4'

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14-04-x64
    driver_config:
      region: ams3
      size: 512mb

suites:
  - name: default
    run_list:
      - recipe[stackup-base::default]
    attributes:
      apt:
        unattended_upgrades:
          mail: 'foo@example.com'
          automatic_reboot_time: '02:00'
